### ISSUE TITLE
How to change the font-size of post headings

### ISSUE THREAD

**Issue by AlexVPopov** [octothemes/blanket#1]
Hi guys,

First of all, thank you for the beautiful theme, I use it on my Octopress site. Secondly, I apologise for my question as it probably has more to do with my lack of CSS knowledge and the structure of Octopress stylesheets, then with your theme. Nevertheless, I ran into this difficulty: I want to reduce the font size of my post titles, as I find them a bit too large. I won't bore you with the steps I tried, as none of them worked. So my question - which files should I modify in order to make the titles of my posts a bit smaller? Thank you very much.

P.S. My [site](http://alexvpopov.github.io/) for reference.

**Comment by liangzan** [comment]
Hi Alex,

Thanks for the support! I guess it should be here https://github.com/octothemes/blanket/blob/master/sass/base/_typography.scss#L17

It's pretty simple, Just take a look at the markup, and try to find the css selector for it. Hope this helps!
