### ISSUE TITLE
Article doesn't appear to have any formatting

### ISSUE THREAD

**Issue by emacsen** [octothemes/blanket#2]
Using the current octopress as of two days ago, I tried installing this theme, and the are with the article (I believe it's the "content" div) doesn't appear to have any formatting on it, just the plain default white background, no font, and it also doesn't appear to display the datestamp of the article.

This is a really beautiful theme, and I'd love to use it on my site. Is there a way it can be updated?

**Comment by liangzan** [comment]
Thanks for the compliments. Unfortunately I don't have the time to maintain the project anymore.
